# Generated by Django 6.0.5 on 2026-05-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('duration', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
